packageExtensions:
  "@storybook/core-server@*":
    peerDependencies:
      esbuild-loader: "*"
  "@storybook/core@*":
    peerDependencies:
      esbuild-loader: "*"
  "@storybook/manager-webpack4@*":
    peerDependencies:
      esbuild-loader: "*"
  "@storybook/react@*":
    peerDependencies:
      esbuild-loader: "*"
  app-builder-lib@*:
    peerDependenciesMeta:
      dmg-builder:
        optional: true
  devtools@*:
    dependencies:
      debug: "*"
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint-config-airbnb-base: ">=14"
  storybook-addon-turbo-build@*:
    peerDependencies:
      webpack: "*"
  storycrawler@*:
    peerDependencies:
      puppeteer: ">=5"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
