packageExtensions:
  app-builder-lib@*:
    peerDependenciesMeta:
      dmg-builder:
        optional: true
  devtools@*:
    dependencies:
      debug: "*"
  storycrawler@*:
    peerDependencies:
      puppeteer: ">=5"

  "@storybook/core@*":
    peerDependencies:
      esbuild-loader: "*"

  "@storybook/react@*":
    peerDependencies:
      esbuild-loader: "*"

  storybook-addon-turbo-build@*:
    peerDependencies:
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
