yarnPath: ".yarn/releases/yarn-berry.cjs"
enableGlobalCache: true
packageExtensions:
  "app-builder-lib@*":
    peerDependenciesMeta:
      "dmg-builder":
        optional: true
  "storycrawler@*":
    peerDependencies:
      "puppeteer": ">=5"
  "devtools@*":
    dependencies:
      "debug": "*"
