packageExtensions:
  app-builder-lib@*:
    peerDependenciesMeta:
      dmg-builder:
        optional: true
  devtools@*:
    dependencies:
      debug: "*"
  storycrawler@*:
    peerDependencies:
      puppeteer: ">=5"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
