# This docker image is used to deploy @betaflight/api-server
# in mocked mode to heroku. Used to allow the demo app to
# use the API
FROM node:12-alpine as build

WORKDIR /build
COPY packages packages
COPY types types
COPY .yarn .yarn
COPY tsconfig.build.json \
        tsconfig.base.json \
        tsconfig.cjs.build.json \
        yarn.lock package.json \
        codegen.yml \
        .gitignore \
        .yarnrc.yml \
        ./

# Build the minimum required to make a functional mock server
RUN rm packages/configurator/package.json && \
        yarn --immutable --skip-builds && \
        yarn codegen && yarn build:lib && rm -r packages/configurator

# Deployed layer
FROM node:12-alpine

WORKDIR /mock-server
COPY --from=build /build/packages /mock-server/packages
COPY scripts scripts
COPY yarn.lock package.json .yarnrc.yml ./

RUN yarn workspaces focus --production

WORKDIR /mock-server/packages/api-server
CMD node mock-server.js
